### PR TITLE
V1

### PR DESCRIPTION
**Pull request by rt2zz**
WIP

- Add testbed
- Add basic tests
- Add local podspec
- Promises
- getInitSessionResultPatiently -> getInitSession
- Readme & Installation docs

### CODE REVIEW

**Comment by aaustin** [comment]
Exciting!! This is a big checkin. Looking for code review or are we ready to merge in?

**Comment by aaustin** [comment]
Also: I'm seeing some conflicts with master. Able to resolve them?

**Comment by rt2zz** [comment]
@aaustin just rebased so it will merge clean now. 

I am going to do some further testing and documentation and target tomorrow for merging it in.

Notable breaking changes:
- Switch from callbacks to promise based api, as async/await is the generally preferred RN pattern.
- Rename `getInitSessionPatiently` to `getInitSession`. This is purely a vanity change. Most consumers will be using `subscribe`.
- Removed (in-module) Podfile in favor of .podspec which can be referenced from the consuming project's Podfile. 
- Moved android src from `com.dispatcher` -> `io.branch`

**Comment by rt2zz** [comment]
Merging now in preparation for new features

**Pull request merged**
